version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    volumes:
      # seeding scripts
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

volumes:
  mongodb:
  mongoconfig:
