name: Continuous Integration
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the stack
      run: docker-compose up -d --build

    - name: Check containers
      run: docker ps
    
    - name: Run Unittest
      run: docker run satellite_dash_app_1 pytest tests/satellite_test.py
      #run: docker-compose exec -T satellite_dash_app_1 pytest tests/satellite_test.py
