name: Continuous Integration
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the stack
      run: docker-compose up -d --build

    - name: Check containers
      run: docker ps
    
    - name: Run Unittest
      run: | 
        docker exec satellite_dash_app_1 pytest tests/satellite_test.py
        docker exec satellite_dash_app_1 pytest tests/mongo_test.py

    - name: Login to docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag image
      run: docker tag satellite_dash_app fmpmorgado/satellite_dash-app:latest

    - name: Push image
      run: docker push fmpmorgado/satellite_dash-app:latest
