name: Continuous Integration
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the stack
      run: docker-compose up -d --build

    - name: UnitTest with pytest
      run: docker ps
      #run: |
      #  docker-compose exec -T satellite_dash-app-1 pytest tests/mongo_test.py
      #  docker-compose exec -T satellite_dash-app-1 pytest tests/satellite_test.py
